[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "rm -rf node_modules/.cache node_modules 2>/dev/null || true",
  "npm ci --no-audit --no-fund"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
